package:
  name: pdfkit
  version: 0.5.1

source:
  git_url: https://github.com/Geosyntec/python-pdfkit.git
  git_tag: 0.5.1geo
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: False
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - pdfkit

  # commands:
  #   - py.test

  requires:
    - pytest

about:
  home: https://github.com/Geosyntec/python-pdfkit.git
  license:  MIT License
  summary: 'Wkhtmltopdf python wrapper to convert html to pdf using the webkit rendering engine and qt'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
